# grafana main.yml
# https://hub.docker.com/r/grafana/grafana
---

- name: create isolation user and group. Enable linger
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user.yml
  vars:
    user: "{{ app_user }}"
    uid: "{{ app_uid }}"
    group: "{{ app_group }}"
    gid: "{{ app_gid }}"
    comment: "grafana app account"

- name: install grafana container
  ansible.builtin.import_tasks: podman.yml
  when: containers and ansible_os_family == "RedHat"
  tags:
    - grafana
