# fedora.yml
# apple timecapsule on fedora
---
- name: install samba, avahi, and avahi-tools
  ansible.builtin.package:
    name:
      - samba
      - avahi
      - avahi-tools
    state: latest  # noqa package-latest
  tags:
    - timecap

- name: create smb.d folder for config files
  ansible.builtin.file:
    path: /etc/samba/smb.d
    owner: root
    group: root
    mode: '0755'
    state: directory
  tags:
    - timecap

- name: add include statement to smb.conf file
  ansible.builtin.lineinfile:
    path: /etc/samba/smb.conf
    state: present
    regexp: '^include =$'
    line: 'include = /etc/samba/smb.d/{{ app_name }}.conf'
  tags:
    - timecap

- name: add timecap.conf file to smb.d
  ansible.builtin.template:
    src: centos_smb.conf.j2
    dest: "/etc/samba/smb.d/{{ app_name }}.conf"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - "{{ administrators }}"
  notify: restart smb
  tags:
    - timecap

- name: configure avahi samba service
  ansible.builtin.template:
    src: centos_avahi.samba.service.j2
    dest: /etc/avahi/services/samba.service
    owner: root
    group: root
    mode: '0644'
  with_items:
    - "{{ administrators }}"
  notify: restart avahi
  tags:
    - timecap
