# timecap/tasks/main.yml
# Apple Timecapsule
#
---
- name: base setup samba and avahi
  ansible.builtin.include_role:
    name: samba
    tasks_from: main.yaml
  tags:
    - timecap

- name: create isolation user and group. Enable linger
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user.yml
  vars:
    user: "{{ app_user }}"
    uid: "{{ app_uid }}"
    group: "{{ app_group }}"
    gid: "{{ app_gid }}"
    comment: "{{ app_name }} account"
  tags:
    - timecap

- name: setup timecap directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0750'
    state: directory
  with_items:
    - "{{ app_path }}/{{ app_name }}"
  tags:
    - timecap

- name: add administrators to timecap group
  ansible.builtin.user:
    name: "{{ item[0] }}"
    groups: "{{ app_group }}"
    append: true
  with_items:
    - "{{ administrators }}"
  tags:
    - timecap

- name: setup user subdirectories
  ansible.builtin.file:
    path: "{{ app_path }}/{{ app_name }}/{{ item[0] }}"
    owner: "{{ item[0] }}"
    group: "{{ item[2] }}"
    mode: '0750'
    state: directory
  with_items:
    - "{{ administrators }}"
  tags:
    - timecap

- name: add per user quotas
  ansible.builtin.template:
    src: com.apple.TimeMachine.quota.plist.j2
    dest: "{{ app_path }}/{{ app_name }}/{{ item[0] }}/.com.apple.TimeMachine.Quota.plist"
    owner: "{{ item[0] }}"
    group: "{{ item[2] }}"
    mode: '0644'
  with_items:
    - "{{ administrators }}"
  tags:
    - timecap

- name: add include statement to smb.conf file
  ansible.builtin.lineinfile:
    path: /etc/samba/smb.conf
    state: present
    regexp: '^include =$'
    line: 'include = /etc/samba/smb.d/{{ app_name }}.conf'
  tags:
    - timecap

- name: add timecap.conf file to smb.d
  ansible.builtin.template:
    src: centos_smb.timecap.conf.j2
    dest: "/etc/samba/smb.d/{{ app_name }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: restart smb
  tags:
    - timecap

- name: configure avahi samba service
  ansible.builtin.template:
    src: centos_avahi.samba.service.j2
    dest: /etc/avahi/services/samba.service
    owner: root
    group: root
    mode: '0644'
  notify: restart avahi
  tags:
    - timecap
