# initial setup
# Used for Vagrant images as well as setting up a new box for ansible use
---
- name: provision play
  hosts: all
  become: true
  gather_facts: true

  roles:
    - common

  handlers:
    - name: restart system
      ansible.builtin.reboot:

    - name: reload network
      ansible.builtin.systemd:
        daemon-reload: true
        name: network
        state: reloaded

    - name: reload network Debian
      ansible.builtin.systemd:
        daemon-reload: true
        name: networking
        state: restarted
