# vagrant.yml
---
- name: Vagrant provision play
  hosts: all
  become: true
  gather_facts: true

  roles:
    - common

  handlers:
    - name: restart system
      ansible.builtin.reboot:

    - name: reload network
      ansible.builtin.systemd:
        daemon-reload: true
        name: network
        state: reloaded

    - name: reload network Debian
      ansible.builtin.systemd:
        daemon-reload: true
        name: networking
        state: restarted

