# play-rpi2b.yaml
---

- hosts: rpi2b
  become: true

  roles:
    - common
    - sshd
    - zram
    - rpi2b_setup
    - base-nginx
    - hd-idle
    - irssi
    - wakeonwin
    - piglow
    - munin-node
    - pihole

  handlers:
    - name: restart system
      ansible.builtin.reboot:

    - name: reload network
      ansible.builtin.systemd:
        name: network
        state: reloaded

    - name: reload network Debian
      ansible.builtin.systemd:
        name: networking
        state: restarted

    - name: reload sshd
      ansible.builtin.service:
        name: sshd
        state: reloaded

    - name: reload nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded

    - name: restart smb
      ansible.builtin.systemd:
        name: smb
        enabled: true
        state: restarted

    - name: restart avahi
      ansible.builtin.systemd:
        name: avahi-daemon
        enabled: true
        state: restarted

    - name: reload network Debian
      ansible.builtin.systemd:
        name: networking
        state: restarted

    - name: reload firewall
      ansible.builtin.systemd:
        name: firewalld
        state: restarted
