# Blog Playbook
---

- hosts: blog
  become: true

  roles:
    - blog

  handlers:
    - name: reload network
      ansible.builtin.systemd:
        name: network
        state: reloaded

    - name: reload nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
