# flexget container
---

- name: create flexget conf directory
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0775'
    state: directory
  with_items:
    - "{{ containers_path }}/{{ app_user }}/flexget_conf"

- name: install flexget_conf.yml template
  ansible.builtin.template:
    src: templates/flexget_config.yml.j2
    dest: "{{ containers_path }}/{{ app_user }}/flexget_conf/config.yml"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0640'

- name: build flexget container
  become_user: "{{ app_user }}"
  containers.podman.podman_container:
    recreate: true
    name: flexget
    hostname: "{{ hostname }}"
    image: ghcr.io/ianhaddock/flexget:latest
    volumes:
      - "{{ containers_path }}/{{ app_user }}/flexget_conf:/config:Z"
      - "{{ app_media }}/watch_folder:/watch_folder:z"
    generate_systemd: {"path": "/home/{{ app_user }}/.config/systemd/user"}
    state: present
  register: container_state

- name: enable and start
  become_user: "{{ app_user }}"
  ansible.builtin.systemd:
    daemon-reload: true
    name: "container-flexget"
    enabled: true
    state: started
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ app_uid }}"
  when: container_state.changed
