# flexget container
---

- name: create flexget conf directory
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0775'
    state: directory
  with_items:
    - "{{ containers_path }}/{{ app_user }}/flexget_conf"

- name: stop flexget container if exists
  become_user: "{{ app_user }}"
  ansible.builtin.systemd:
    name: "container-flexget"
    state: stopped
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ app_uid }}"
  register: app_stop_result
  failed_when: "app_stop_result is failed and 'Could not find the requested service container-' not in app_stop_result.msg"

- name: install flexget_conf.yml template
  ansible.builtin.template:
    src: templates/flexget_config.yml.j2
    dest: "{{ containers_path }}/{{ app_user }}/flexget_conf/config.yml"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0640'

- name: build flexget container
  become_user: "{{ app_user }}"
  containers.podman.podman_container:
    recreate: true
    name: flexget
    hostname: "{{ hostname }}"
    image: ghcr.io/ianhaddock/flexget:0.2
    cpus: 1
    memory: 256M
    env:
      LOG_LEVEL=verbose
      TZ=America/Los_Angeles
    volumes:
      - "{{ containers_path }}/{{ app_user }}/flexget_conf:/config:Z"
      - "{{ app_media }}/watch_folder:/watch_folder:z"
    generate_systemd: {"path": "/home/{{ app_user }}/.config/systemd/user"}
    state: present

- name: enable and start
  become_user: "{{ app_user }}"
  ansible.builtin.systemd:
    daemon-reload: true
    name: "container-flexget"
    enabled: true
    state: started
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ app_uid }}"

- name: create archives path
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  with_items:
    - "{{ archives_path }}/containers"

- name: user crontab backup confg directory weekly
  become_user: root
  ansible.builtin.cron:
    name: flexget - backup config directory weekly
    minute: "45"
    hour: "7"
    weekday: "5"
    job: "/usr/bin/tar czvf {{ archives_path }}/containers/flexget-weekly-config-backup.tar.gz /mnt/containers/{{ app_user }}/flexget_conf"
