# install transmission
---
- name: create isolation user and group. Enable linger
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user.yml
  vars:
    user: "{{ app_user }}"
    uid: "{{ app_uid }}"
    group: "{{ app_group }}"
    gid: "{{ app_gid }}"
    comment: "{{ app_name }} account"
  tags:
    - transmission

- name: add sysctl 00-transmission.conf
  ansible.builtin.template:
    src: 00-transmission.conf.j2
    dest: /etc/sysctl.d/00-transmission.conf
    owner: root
    group: root
    mode: '0640'
  tags:
    - transmission

- name: create directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0775'
    state: directory
  with_items:
    - "{{ containers_path }}/{{ app_user }}/conf"
    - "{{ app_media }}"
    - "{{ app_media }}/complete"
    - "{{ app_media }}/incomplete"
  tags:
    - transmission

- name: create watch_folder with open permissions
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0777'
    state: directory
  with_items:
    - "{{ app_media }}/watch_folder"
  tags:
    - transmission

- name: install in container
  ansible.builtin.import_tasks: podman_transmission.yml
  when: containers and ansible_os_family == "RedHat"
  tags:
    - transmission

- name: install on rpi2b
  ansible.builtin.import_tasks: rpi2b_transmission.yml
  when: ansible_facts.machine == "armv7l"
  tags:
    - transmission

- name: install flexget
  ansible.builtin.import_tasks: flexget.yml
  tags:
    - flexget

- name: seutp motorsort
  ansible.builtin.import_tasks: motorsort.yaml
  tags:
    - motorsort

- name: open app data port on firewall
  ansible.builtin.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "{{ app_data_port }}/udp"
    - "{{ app_data_port }}/tcp"
  tags:
    - transmission

- name: set forward proxy and ports
  ansible.builtin.include_role:
    name: base-nginx
    tasks_from: forward_proxy.yml
    public: true
  when: containers
  tags:
    - transmission
