# install transmission
---
- name: create isolation user and group. Enable linger
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user.yml
  vars:
    user: "{{ app_user }}"
    uid: "{{ app_uid }}"
    group: "{{ app_group }}"
    gid: "{{ app_gid }}"
    comment: "transmission app account"

- name: install transmission
  ansible.builtin.import_tasks: transmission.yml
  when: containers and not ansible_facts.machine == "armv7l"
  tags:
    - transmission

- name: install transmission rpi2b
  ansible.builtin.import_tasks: rpi2b_transmission.yml
  when: ansible_facts.machine == "armv7l"
  tags:
    - transmission

- name: install flexget
  ansible.builtin.import_tasks: flexget.yml
  tags:
    - flexget

- name: open app data port on firewall
  ansible.builtin.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "{{ app_data_port }}/udp"
    - "{{ app_data_port }}/tcp"

- name: set forward proxy and ports
  ansible.builtin.include_role:
    name: base-nginx
    tasks_from: forward_proxy.yml
    public: true
  when: containers
