# gitea install
---
- name: create isolation user and group. Enable linger
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user.yml
  vars:
    user: "{{ app_user }}"
    uid: "{{ app_uid }}"
    group: "{{ app_group }}"
    gid: "{{ app_gid }}"
    comment: "gitea app account"
  tags:
    - gitea

- name: install gitea container
  ansible.builtin.import_tasks: gitea.yml
  tags:
    - gitea

- name: open git ssh port
  ansible.builtin.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "{{ app_ssh_port }}/tcp"
  tags:
    - gitea

- name: set hosts files entries
  ansible.builtin.import_tasks: hosts_file.yml
  tags:
    - gitea

- name: set forward proxy and http port
  ansible.builtin.include_role:
    name: base-nginx
    tasks_from: forward_proxy.yml
    public: true
  when: containers
  tags:
    - gitea
