# hd-idle main.yml
---
- name: install hd-idle and related tools
  ansible.builtin.package:
    name:
      - smartmontools
      - hdparm
      - hd-idle
    state: latest  # noqa package-latest
  tags:
    - hd-idle

- name: update hd-idle defaults file
  ansible.builtin.template:
    src: 'etc_defaults_hd-idle'
    dest: '/etc/default/hd-idle'
    owner: root
    group: root
    mode: '0644'
  tags:
    - hd-idle

- name: enable and start hd-idle service
  ansible.builtin.systemd:
    daemon-reload: true
    name: hd-idle
    enabled: true
    state: started
  tags:
    - hd-idle

- name: create log file
  ansible.builtin.file:
    path: /var/log/hd-idle.log
    owner: root
    group: root
    mode: '0644'
    state: touch
  tags:
    - hd-idle
