# standard user creation
---
- name: create group
  ansible.builtin.group:
    name: "{{ group }}"
    gid: "{{ gid }}"
  tags:
    - ac_backup
    - gitea
    - isos
    - minio

- name: create user
  ansible.builtin.user:
    name: "{{ user }}"
    group: "{{ group }}"
    uid: "{{ uid }}"
    comment: "{{ comment }}"
    generate_ssh_key: true
    ssh_key_file: ".ssh/{{ user }}"
  tags:
    - ac_backup
    - gitea
    - isos
    - minio

- name: check if linger is enabled
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ user }}"
  when: containers
  tags:
    - ac_backup
    - gitea
    - minio

- name: enable linger
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ user }}"
  when: containers
  tags:
    - ac_backup
    - gitea
    - minio

- name: add XDG_RUNTIME_DIR to .bashrc as a workaround to systemd-nspawn
  ansible.builtin.lineinfile:
    path: "/home/{{ user }}/.bashrc"
    line: 'export XDG_RUNTIME_DIR=/run/user/$UID'
    regexp: '^export XDG_RUNTIME_DIR'
  tags:
    - ac_backup
    - gitea
    - minio

    # - name: install systemd-container package for machinectl
    #  so this is the new way to switch users with a clean login environment
    #  has to do with changes to systemd and its vm & container handling
    #  but its not simple to remember:
    #  https://unix.stackexchange.com/questions/346841/\
    #  why-does-sudo-i-not-set-xdg-runtime-dir-for-the-target-user
    #  e.g. # machinectl shell --uid=$(id -u user)
    #  so for now I'm leaving the cheap fix of exporting the XDG_RUNTIME_DIR
    #  in .bashrc on login
