# main.yml
#
---
- name: create isolation user and group. Enable linger
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user.yml
  vars:
    user: "{{ app_user }}"
    uid: "{{ app_uid }}"
    group: "{{ app_group }}"
    gid: "{{ app_gid }}"
    comment: "{{ app_name }} account"

- name: add user to groups
  ansible.builtin.user:
    name: "{{ app_user }}"
    groups: "{{ append_groups }}"
    append: true

- name: create media directories for plex
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
    state: directory
  with_items:
    - "{{ media_path }}/audiobooks"
    - "{{ media_path }}/books"
    - "{{ media_path }}/lemans"
    - "{{ media_path }}/movies"
    - "{{ media_path }}/music"
    - "{{ media_path }}/staging"
    - "{{ media_path }}/tvshows"
    - "{{ media_path }}/yoga"
    - "{{ media_path }}/youtube"
    - "{{ media_path }}/yt_tunes"

- name: install plex container
  ansible.builtin.import_tasks: podman_plex.yml
  when: containers and ansible_os_family == "RedHat"
  tags:
    - plex

- name: install plex on rpi2b
  ansible.builtin.import_tasks: rpi2b_plex.yml
  when: ansible_facts.machine == "armv7l"
  tags:
    - plex

- name: install plex plugins
  ansible.builtin.import_tasks: plugins.yml
  tags:
    - plex

- name: install yt-dlp scripts
  ansible.builtin.import_tasks: ytdlp_scripts.yml
  when: containers and ansible_os_family == "RedHat"

- name: set plex container forward proxy and ports
  ansible.builtin.include_role:
    name: base-nginx
    tasks_from: forward_proxy.yml
    public: true
  when: containers and ansible_os_family == "RedHat"

- name: set rpi2b forward proxy and ports
  ansible.builtin.include_role:
    name: base-nginx
    tasks_from: forward_proxy.yml
  vars:
    app_port: 32400
    app_name: plex
  when: ansible_facts.machine == "armv7l"
