# rpi2b_plex.yml
---
- name: create directories for plex
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
    state: directory
  with_items:
    - "{{ containers_path }}/{{ app_name }}/config/Library/Application Support"
    - "{{ containers_path }}/{{ app_name }}/transcode"

- name: check if plex is already installed
  ansible.builtin.stat:
    path: "{{ containers_path }}/{{ app_name }}/{{ plex_server_dir }}"
  register: plex_path

- name: downlaod latest plexmediaserver
  ansible.builtin.get_url:
    url: "https://plex.tv/downloads/latest/5?channel=16&build=linux-armv7neon&distro=debian&X-Plex-Token=xxxxxxxxxxxxxxxxxxxx"
    dest: "{{ containers_path }}/{{ app_name }}/plexmediaserver.deb"
      #  when: not plex_path.stat.exists

- name: install or update plexmediaserver
  ansible.builtin.apt:
    deb: "{{ containers_path }}/{{ app_name }}/plexmediaserver.deb"
      #  when: not plex_path.stat.exists

- name: copy Plex Media Server folder to {{ containers_path }}/plex
  ansible.builtin.copy:
    src: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server"
    dest: "{{ containers_path }}/{{ app_name }}/config/Library/Application Support/"
    remote_src: true
  when: not plex_path.stat.exists

- name: remove Plex Media Server from var/lib before symlinking
  ansible.builtin.file:
    path: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server" 
    state: absent
  when: not plex_path.stat.exists

- name: link config
  ansible.builtin.file:
    src: "{{ containers_path }}/{{ app_name }}/{{ plex_server_dir }}"
    dest: "/var/lib/plexmediaserver/Library/Application Support/"
    owner: root
    group: root
    state: link
  when: not plex_path.stat.exists
